[workspace]
members = ["crates/xcfx-node", "crates/xcfx-node-napi"]
resolver = "3"

[workspace.package]
version = "0.8.0"
edition = "2024"
rust-version = "1.97.1"
license = "MIT"
repository = "https://github.com/iosh/xcfx-node"


[workspace.dependencies]
cfxkey = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
cfx-executor = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
cfx-internal-common = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
cfx-mpt = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
cfx-parameters = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
cfx-rpc-eth-types = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
cfx-statedb = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
cfx-storage-types = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
cfx-types = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
cfx-vm-types = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
primitives = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
diem-crypto = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
diem-types = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }
pow-types = { git = "https://github.com/iosh/conflux-rust", branch = "v3.1.0" }

rustc-hex = "2"
thiserror = "2"
rlp = "0.6"
keccak-hash = "0.12"
