[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "xcfx_node"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
cfxcore = { git = "https://github.com/Conflux-Chain/conflux-rust.git" }
napi = "2"
napi-derive = "2"
client = { git = "https://github.com/Conflux-Chain/conflux-rust.git" }
chrono = "0.4.38"
parking_lot = "0.11"
log = "0.4"
[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
codegen-units = 1
