[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "xcfx_node"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0-alpha.13"
napi-derive = "3.0.0-alpha.13"

cfxcore = { git = "https://github.com/Conflux-Chain/conflux-rust.git", rev = "2d82c4bde7f6253395bb99a19cf8bc3bc2488534" }
primitives = { git = "https://github.com/Conflux-Chain/conflux-rust.git", rev = "2d82c4bde7f6253395bb99a19cf8bc3bc2488534" }
client = { git = "https://github.com/Conflux-Chain/conflux-rust.git", rev = "2d82c4bde7f6253395bb99a19cf8bc3bc2488534" }

chrono = "0.4.38"
parking_lot = "0.11"
log = "0.4"
tempfile = "3"
log4rs = { version = "1.2.0", features = ["background_rotation", "gzip"] }
[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
codegen-units = 1
