/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ConfluxNode {
  constructor()\n startNode(config: ConfluxConfig): Promise<void>\n stopNode(): Promise<void>
}

export interface ConfluxConfig {
  configFile?: string\n/**
   * Set the node type to Full node, Archive node, or Light node.
   *  Possible values are "full", "archive",or "light".
   * @default "full"
   */
  nodeType?: string\n/**
   * Database type to store block-related data.
   * Supported: rocksdb, sqlite.
   * @default sqlite
   */
  blockDbType?: string\n/**
   * Add data directory configuration
   * The conflux node will use this directory to store data.  If not set, a temporary directory will be used.
   * @default: temp dir
   */
  confluxDataDir?: string\n/**
   * Add block db directory configuration
   * @default: conflux_data_dir + blockchain_db
   */
  blockDbDir?: string\n/**
   * Add netconf directory configuration
   * @default: conflux_data_dir + net_config
   */
  netconfDir?: string\n/**
   * The chain ID of the network.(core space)
   * @default 1234
   */
  chainId?: number\n/**
   * The chain ID of the network.( eSpace)
   *  @default 1235
   */
  evmChainId?: number\n/** bootnodes is a list of nodes that a conflux node trusts, and will be used to sync the blockchain when a node starts. */
  bootnodes?: string\n/** mining_author is the address to receive mining rewards. */
  miningAuthor?: string\n/**
   * Listen address for stratum
   * @default "127.0.0.1"
   */
  stratumListenAddress?: string\n/**
   * `mining_type` is the type of mining.
   * stratum | cpu | disable
   */
  miningType?: string\n/** Port for stratum. */
  stratumPort?: number\n/** Secret key for stratum. The value is 64-digit hex string. If not set, the RPC subscription will not check the authorization. */
  stratumSecret?: string\n/** Window size for PoW manager */
  powProblemWindowSize?: number\n/**
   * If it's not set, blocks will only be generated after receiving a transaction.Otherwise,
   * the blocks are automatically generated every
   */
  devBlockIntervalMs?: number\n/**
   * If it's `true`, `DEFERRED_STATE_EPOCH_COUNT` blocks are generated after
   * receiving a new tx through RPC calling to pack and execute this
   * transaction
   */
  devPackTxImmediately?: boolean\n/** The private key of the genesis (core space), every account will be receive 10000 CFX */
  genesisSecrets?: Array<string>\n/** The private key of the genesis (eSpace), every account will be receive 10000 CFX */
  genesisEvmSecrets?: Array<string>\n/**
   * `tcp_port` is the TCP port that the process listens for P2P messages. The default is 32323.
   * @default 32323
   */
  tcpPort?: number\n/**
   * `udp_port` is the UDP port used for node discovery.
   * @default 32323
   */
  udpPort?: number\n/** `public_address` is the address of this node used */
  publicAddress?: string\n/**
   * Possible Core space names are: all, safe, cfx, pos, debug, pubsub, test, trace, txpool.
   * `safe` only includes `cfx` and `pubsub`, `txpool`.
   *  @default "all"
   */
  publicRpcApis?: string\n/**
   * Possible eSpace names are: eth, ethpubsub, ethdebug.
   *  @default 'evm'
   */
  publicEvmRpcApis?: string\n/**
   * The port of the websocket JSON-RPC server(public_rpc_apis is user defined).
   * if not set, the JSON-RPC server will not be started.
   * @default null
   */
  jsonrpcWsPort?: number\n/**
   * The port of the http JSON-RPC server.public_rpc_apis is user defined).
   * if not set, the JSON-RPC server will not be started.
   * @default null
   */
  jsonrpcHttpPort?: number\n/**
   * The port of the tcp JSON-RPC server. public_rpc_apis is user defined).
   * if not set, the JSON-RPC server will not be started.
   * @default null
   */
  jsonrpcTcpPort?: number\n/**
   * The port of the http JSON-RPC server public_rpc_apis is user defined).
   * if not set, the JSON-RPC server will not be started.
   * @default null
   */
  jsonrpcHttpEthPort?: number\n/**
   * The port of the websocket JSON-RPC serverpublic_rpc_apis is user defined).
   * if not set, the JSON-RPC server will not be started.
   * @default null
   */
  jsonrpcWsEthPort?: number\n/**
   * The port of the tcp JSON-RPC server(public_rpc_apis is "all").
   * if not set, the JSON-RPC server will not be started.
   * @default null
   */
  jsonrpcLocalTcpPort?: number\n/**
   * The port of the http JSON-RPC server(public_rpc_apis is "all").
   * if not set, the JSON-RPC server will not be started.
   * @default null
   */
  jsonrpcLocalHttpPort?: number\n/**
   * The port of the websocket JSON-RPC server(public_rpc_apis is "all").
   * if not set, the JSON-RPC server will not be started.
   * @default null
   */
  jsonrpcLocalWsPort?: number\n/**
   * `jsonrpc_http_keep_alive` is used to control whether to set KeepAlive for rpc HTTP connections.
   * @default false
   */
  jsonrpcHttpKeepAlive?: boolean\n/**
   * The password used to encrypt the private key of the pos_private_key.
   *  @default "123456"
   */
  devPosPrivateKeyEncryptionPassword?: string\n/** @default:0 */
  posReferenceEnableHeight?: number\n/** pos config path */
  posConfigPath?: string\n/** pos initial_nodes.json path */
  posInitialNodesPath?: string\n/** pos pos_key file path */
  posPrivateKeyPath?: string\n/** @default:1 */
  defaultTransitionTime?: number\n/** @default:1 */
  cip1559TransitionHeight?: number\n/**
   * Enable CIP43A, CIP64, CIP71, CIP78A, CIP92 after hydra_transition_number
   * @default:1
   */
  hydraTransitionNumber?: number\n/**
   * Enable cip76, cip86 after hydra_transition_height
   * @default:1
   */
  hydraTransitionHeight?: number\n/**
   * Enable cip112 after hydra_transition_height
   * @default:1
   */
  cip112TransitionHeight?: number\n/** log_conf` the path of the log4rs configuration file. The configuration in the file will overwrite the value set by `log_level`. */
  logConf?: string\n/**
   * log_level` is the printed log level.
   * "error" | "warn" | "info" | "debug" | "trace" | "off"
   */
  logLevel?: string\n/** `print_memory_usage_period_s` is the period for printing memory usage. */
  printMemoryUsagePeriodS?: number\n/**
   * `poll_lifetime_in_seconds` is the lifetime of the poll in seconds.
   * If set, the following RPC methods will be enabled:
   * - `cfx_newFilter` `cfx_newBlockFilter` `cfx_newPendingTransactionFilter` `cfx_getFilterChanges` `cfx_getFilterLogs` `cfx_uninstallFilter`.
   * - `eth_newFilter` `eth_newBlockFilter` `eth_newPendingTransactionFilter` eth_getFilterChanges eth_getFilterLogs eth_uninstallFilter
   * @default: 600
   */
  pollLifetimeInSeconds?: number\n/** if `get_logs_filter_max_limit` is configured but the query would return more logs */
  getLogsFilterMaxLimit?: number
}
