[target.x86_64-unknown-linux-gnu]
dockerfile = "./dockers/x86_64-unknown-linux-gnu"
[target.x86_64-unknown-linux-gnu.env]
CROSS_NO_WARNINGS = "0"

[target.aarch64-unknown-linux-gnu]
dockerfile = "./dockers/aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu.env]
CROSS_NO_WARNINGS = "0"
