
base:
  role: validator
  waypoint:
    from_config: 0:35ce891dd087903454e5ef41e4807dfdf97f62f8189bae96271da3c5b59b12c5
consensus:
  round_initial_timeout_ms: 60000
  safety_rules:
    service:
      type: local
execution:
  genesis_file_location: ./genesis_file
logger:
  file: ./log/pos.log
  level: INFO