[package]
name = "xcfx-node"
description = "Rust product library for xcfx-node"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cfxkey.workspace = true
cfx-executor.workspace = true
cfx-internal-common.workspace = true
cfx-mpt.workspace = true
cfx-parameters.workspace = true
cfx-rpc-eth-types.workspace = true
cfx-statedb.workspace = true
cfx-storage-types.workspace = true
cfx-types.workspace = true
cfx-vm-types.workspace = true
primitives.workspace = true
rustc-hex.workspace = true
thiserror.workspace = true
diem-crypto.workspace = true
diem-types.workspace = true
pow-types.workspace = true
rlp.workspace = true
keccak-hash.workspace = true

[dev-dependencies]
hex-literal = "1"
rand = "0.8"
