[package]
name = "xcfx-node"
description = "Rust product library for xcfx-node"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cfx-internal-common.workspace = true
cfx-mpt.workspace = true
cfx-storage-types.workspace = true
primitives.workspace = true
thiserror.workspace = true
